spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/backend3
    driver-class-name: org.postgresql.Driver
    username: db3_user
    password: db3_password
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /
    logging:
      request:
        enable: true

jwt:
  secret: E9vbBG70kXggGNMeNcSIyeYdXR1mgPRQX3y77TdMZLo=
  expiration: 900000

logging:
  level:
    root: DEBUG
    org.springframework: ERROR # Spring Framework
    org.hibernate: DEBUG # Hibernate
    org.hibernate.SQL: DEBUG # SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Parameter binding
    org.springframework.web: DEBUG # Web requests
    org.springframework.security: DEBUG # Spring Security
    com.dl4m.backend3: DEBUG # Your application
    org.apache.catalina.filters.HttpHeaderSecurityFilter: DEBUG # Tomcat header security
    org.apache.catalina.filters.RemoteIpFilter: DEBUG # Tomcat remote IP filter
    org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/]: TRACE # Tomcat request tracing
    org.apache.catalina.session: DEBUG # Tomcat session logging
    org.apache.tomcat.util.net: DEBUG # Tomcat network logging
    org.apache.coyote: DEBUG # Coyote logs
    org.springframework.boot.devtools: ERROR # Spring Boot DevTools
    org.postgresql: DEBUG # PostgreSQL driver
    org.springframework.boot.test: DEBUG # Spring Boot Test
    org.junit: DEBUG # JUnit
    com.h2database: DEBUG # H2 database
    io.jsonwebtoken: DEBUG # JJWT
    org.springframework.data.jpa: DEBUG #spring data jpa
    org.springframework.validation: DEBUG #Spring validation