spring:
  datasource:
    url: jdbc:postgresql:///backend3?cloudSqlInstance=devlife4me-generic-apps:us-central1:backend3-postgresql-dev&socketFactory=com.google.cloud.sql.postgres.SocketFactory&sslmode=disable
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      cloud-sql:
        socket-factory: com.google.cloud.sql.postgres.SocketFactory
        cloud-sql-instance: devlife4me-generic-apps:us-central1:backend3-postgresql-dev
        ssl-mode: disable

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /
  error:
    include-message: always

jwt:
  expiration: 900000

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.catalina: DEBUG
    org.apache.coyote: DEBUG
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.pool: TRACE
    com.dl4m.backend3: DEBUG
